# Generated by Django 2.2.2 on 2019-06-11 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fan_fictions', '0009_entry_author'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='comment_entry',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fan_fictions.Story'),
            preserve_default=False,
        ),
    ]
