# Generated by Django 2.2.2 on 2019-06-11 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_comment_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_entry',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_story',
            new_name='story',
        ),
    ]
