# Generated by Django 2.2.2 on 2019-11-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190720_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='profile_picture',
            field=models.CharField(max_length=100),
        ),
    ]
