# Generated by Django 2.2.2 on 2019-06-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_fictions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default='no title', max_length=50),
            preserve_default=False,
        ),
    ]
