# Generated by Django 2.2.2 on 2019-06-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_fictions', '0003_story_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='story',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
