# Generated by Django 2.2.2 on 2019-06-10 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_fictions', '0007_auto_20190610_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='author',
        ),
    ]
