# Generated by Django 2.2.2 on 2019-11-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_fictions', '0010_auto_20191110_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_cover',
            field=models.URLField(),
        ),
    ]
